#DeepTrap config
train_data_path: /orange/ewhite/b.weinstein/CameraTrap/iWildCam_2019_CCT/iWildCam_2019_CCT_images/
test_data_path: /orange/ewhite/b.weinstein/CameraTrap/iWildCam_2019_IDFG/iWildCam_IDFG_images/

#Preprocessing
train_h5_dir: /orange/ewhite/b.weinstein/CameraTrap/preprocessed/train/
test_h5_dir: /orange/ewhite/b.weinstein/CameraTrap/preprocessed/test/
num_hipergator_workers: 20

height: 299
width: 299

#Training
bgmodel:
    epochs: 1
    batch_size: 1
classification_model:
    gpus: 1
    epochs: 10
    batch_size: 32

