#DeepTrap config
train_data_path: /orange/ewhite/b.weinstein/CameraTrap/iWildCam_2019_CCT/iWildCam_2019_CCT_images/
test_data_path: /orange/ewhite/b.weinstein/CameraTrap/iWildCam_2019_IDFG/iWildCam_IDFG_images/
detector_path: 

#Preprocessing
output_dir: /orange/ewhite/b.weinstein/CameraTrap/preprocessed/

#Training
bgmodel:
    epochs: 1
    batch_size: 1
classification_model:
    image_size: 299
    gpus: 1
    epochs: 1
    batch_size: 32

